service: zeedstudio
provider:
  name: aws
  runtime: nodejs14.x
  region: ap-south-1
  memorySize: 128
  iamRoleStatements:
    -  Effect: "Allow"
       Action: '*'
       Resource: "*"
functions:
  api:
    handler: index.handler
    events:
      - httpApi: '*'